development:
  adapter: mysql
  database: ftb_development
  username: root
  password: password
  host: localhost

test:
  adapter: mysql
  database: ftb_test
  username: root
  password: password
  host: localhost

production:
  adapter: mysql
  database: ftb_production
  username: root
  password: password
  host: localhost
